model:
  base_learning_rate: 4.5e-6
  target: taming.models.vqgan_top.VQModel
  params:
    ddconfig:
      embed_dim: 256
      n_embed1: 1024
      beta: 0.25
      resolution: 256
      in_channels: 3
      out_channels: 3
      ch: 128
      num_res_blocks: 2
      down_f: 8
      ch_mult: [ 1,1,2,2,4]  # num_down = len(ch_mult)-1
      dropout: 0.0

    lossconfig:
      target: taming.modules.losses.vqperceptual.VQLPIPSWithDiscriminator
      params:
        disc_conditional: False
        disc_in_channels: 3
        disc_start: 10000
        disc_weight: 0.8
        codebook_weight: 1.0

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 4
    num_workers: 4
    train:
      target: taming.data.augment_custom.CustomTrain
      params:
        dirpath: # ToBeModified
        training_images_list_file: data/train.txt
        size: 256
    validation:
      target: taming.data.augment_custom.CustomTest
      params:
        dirpath: # ToBeModified
        test_images_list_file: data/test.txt
        size: 256

